name: Deploy price mates to s3

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: sleep 5
      - run: ls
      - run: cd out && ls -la

      # outputs the build for the next step to use
      - uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: out

  push-to-s3:
    needs: lint-and-build
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      # gets the /out folder from the previous step
      - uses: actions/download-artifact@v2
        with:
          name: build-output
          path: out

      # pushes to s3 on main executions
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - run: aws s3 sync ./out s3://price-mates-landing-page --delete
